capital:
  initial: 10000
  trade_size: 1000
data:
  path: data/PEPE_1m.csv
entry_conditions:
  macd:
    crossover: bullish
    fast_period: 12
    signal_period: 9
    slow_period: 26
  price_move:
    percentage: 2.0
  pullback:
    percentage: 0.8
  rsi:
    condition: below
    period: 14
    threshold: 33
exit_conditions:
  holding_period: 11
  stop_loss: 2.5
  take_profit: 1.1
symbol: BTCUSDT
timeframe: 1m
